name = "sebongclinic"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "sebongclinic-db"
database_id = "de61fb37-3f20-403e-a6dd-72dccf964fe1"
